apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: elin-stub-ws
  labels:
    team: bidrag     
spec:
  port: 8080
  liveness:
    path: /services/health/isAlive
    initialDelay: 15
    periodSeconds: 2
    failureThreshold: 120
  readiness:
    path: /services/health/isReady
    initialDelay: 15
    periodSeconds: 2
    failureThreshold: 120
  replicas:
      min: 1
      max: 1
      cpuThresholdPercentage: 90
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi             
prometheus:
  enabled: true
  path: /system/prometheus    
vault:
  enabled: true
