-- Table: public.fnr

-- DROP TABLE public.fnr;

CREATE TABLE public.fnr
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fnr character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT fnr_pkey PRIMARY KEY (id),
    CONSTRAINT uk_80tfrd6j85uej0aug8o32wvj1 UNIQUE (fnr)

)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.fnr
    OWNER to "elin-stub-db-t6-admin";
    
GRANT ALL ON TABLE public.fnr TO "elin-stub-db-t6-admin";
GRANT ALL ON TABLE public.fnr TO "elin-stub-db-t6-user" WITH GRANT OPTION;

-- Table: public.rolle

-- DROP TABLE public.rolle;

CREATE TABLE public.rolle
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    rolle_type character varying(255) COLLATE pg_catalog."default",
    fk_fnr integer,
    CONSTRAINT rolle_pkey PRIMARY KEY (id),
    CONSTRAINT fk211d3v5cphsvxe024mrkoy4a9 FOREIGN KEY (fk_fnr)
        REFERENCES public.fnr (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.rolle
    OWNER to "elin-stub-db-t6-admin";
    
GRANT ALL ON TABLE public.rolle TO "elin-stub-db-t6-admin";
GRANT ALL ON TABLE public.rolle TO "elin-stub-db-t6-user" WITH GRANT OPTION;
    
-- Table: public.person

-- DROP TABLE public.person;

CREATE TABLE public.person
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    dgjeld_gebyr_ilagtti numeric(19,2),
    dinnbet_belop_uford numeric(19,2),
    dtot_lop_bidrag numeric(19,2),
    faktura_maate_beskr character varying(255) COLLATE pg_catalog."default",
    siste_aktivitet_beskr character varying(255) COLLATE pg_catalog."default",
    status_innkrev_beskr character varying(255) COLLATE pg_catalog."default",
    fk_rolle integer,
    CONSTRAINT person_pkey PRIMARY KEY (id),
    CONSTRAINT uk_hx1eq5i45xxxo5gvaxdenbfyo UNIQUE (fk_rolle),
    CONSTRAINT fk1bxur7wu68s1ed316ii8ou012 FOREIGN KEY (fk_rolle)
        REFERENCES public.rolle (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.person
    OWNER to "elin-stub-db-t6-admin";    

GRANT ALL ON TABLE public.person TO "elin-stub-db-t6-admin";
GRANT ALL ON TABLE public.person TO "elin-stub-db-t6-user" WITH GRANT OPTION;    

-- Table: public.sak

-- DROP TABLE public.sak;

CREATE TABLE public.sak
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    dbm_gjeld_fasts_gebyr numeric(19,2),
    dbm_gjeld_rest numeric(19,2),
    dbp_gjeld_fast_gebyr numeric(19,2),
    saksnr integer,
    fk_rolle_bm integer,
    fk_rolle_bp integer,
    CONSTRAINT sak_pkey PRIMARY KEY (id),
    CONSTRAINT uk_hx1eq5i450u2o5gvabdenbfyi UNIQUE (saksnr)
,
    CONSTRAINT fk267xvm8x9kqoy9xbpijlt3wft FOREIGN KEY (fk_rolle_bp)
        REFERENCES public.rolle (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkki5gdd1rve8ycyyicr31fgmcx FOREIGN KEY (fk_rolle_bm)
        REFERENCES public.rolle (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.sak
    OWNER to "elin-stub-db-t6-admin";

GRANT ALL ON TABLE public.sak TO "elin-stub-db-t6-admin";
GRANT ALL ON TABLE public.sak TO "elin-stub-db-t6-user" WITH GRANT OPTION;

-- Index: saksnr_idx

-- DROP INDEX public.saksnr_idx;

CREATE INDEX saksnr_idx
    ON public.sak USING btree
    (saksnr)
    TABLESPACE pg_default;
    
    
-- Table: public.barn

-- DROP TABLE public.barn;

CREATE TABLE public.barn
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    dbid_utbet_andel character varying(255) COLLATE pg_catalog."default",
    dbid_utbet_tot character varying(255) COLLATE pg_catalog."default",
    dbp_bel_gjeld_off character varying(255) COLLATE pg_catalog."default",
    dbp_bel_gjeld_priv_andel character varying(255) COLLATE pg_catalog."default",
    dbp_bel_gjeld_priv_tot character varying(255) COLLATE pg_catalog."default",
    dforsk_utbet_andel character varying(255) COLLATE pg_catalog."default",
    dforsk_utbet_tot character varying(255) COLLATE pg_catalog."default",
    dtbid_per_siste_dato_fom character varying(255) COLLATE pg_catalog."default",
    dtbid_per_siste_dato_tom character varying(255) COLLATE pg_catalog."default",
    sstopp_ford character varying(255) COLLATE pg_catalog."default",
    fk_rolle integer,
    fk_sak integer,
    CONSTRAINT barn_pkey PRIMARY KEY (id),
    CONSTRAINT fk67tb3uhirjo8jubxy95hv45je FOREIGN KEY (fk_sak)
        REFERENCES public.sak (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkisdt1v29ui8lamodklxmj7r7d FOREIGN KEY (fk_rolle)
        REFERENCES public.rolle (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.barn
    OWNER to "elin-stub-db-t6-admin";
    
GRANT ALL ON TABLE public.barn TO "elin-stub-db-t6-admin";
GRANT ALL ON TABLE public.barn TO "elin-stub-db-t6-user" WITH GRANT OPTION;

-- Table: public.transaksjon

-- DROP TABLE public.transaksjon;

CREATE TABLE public.transaksjon
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    doppr_belop numeric(19,2),
    drest_belop numeric(19,2),
    dtbid_per_dato_fom character varying(255) COLLATE pg_catalog."default",
    dtbid_per_dato_tom character varying(255) COLLATE pg_catalog."default",
    dtpost_dato character varying(255) COLLATE pg_catalog."default",
    dvaluta_oppr_belop numeric(19,2),
    motpost boolean NOT NULL,
    s_sokn_type character varying(255) COLLATE pg_catalog."default",
    sbehand_beskr character varying(255) COLLATE pg_catalog."default",
    sbehand_kode character varying(255) COLLATE pg_catalog."default",
    sbidrag_id character varying(255) COLLATE pg_catalog."default",
    strans_beskr character varying(255) COLLATE pg_catalog."default",
    strans_kode character varying(255) COLLATE pg_catalog."default",
    svaluta_kode character varying(255) COLLATE pg_catalog."default",
    fk_rolle_barn integer,
    fk_rolle_betaler integer,
    fk_rolle_mottaker integer,
    fk_sak integer,
    CONSTRAINT transaksjon_pkey PRIMARY KEY (id),
    CONSTRAINT fkhehnrsmhuu7luj7680igj7e6h FOREIGN KEY (fk_rolle_mottaker)
        REFERENCES public.rolle (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkicwrdvar80wts7fkrv8yqytbq FOREIGN KEY (fk_sak)
        REFERENCES public.sak (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkmcdp6jtq4jytv2x1h7ilxfg4c FOREIGN KEY (fk_rolle_betaler)
        REFERENCES public.rolle (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fknp06xo303hqsg64estfsfyok5 FOREIGN KEY (fk_rolle_barn)
        REFERENCES public.rolle (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.transaksjon
    OWNER to "elin-stub-db-t6-admin";

GRANT ALL ON TABLE public.transaksjon TO "elin-stub-db-t6-admin";
GRANT ALL ON TABLE public.transaksjon TO "elin-stub-db-t6-user" WITH GRANT OPTION;    